<script>
    require.config({
        map: {
            '*': {
                'mainWidget': "https://cdn.accessibly.app/accessibility-widget-v2.min.js",
                'widgetjs': '<?php echo $this->getScriptUrl(); ?>',
            }
        }
    });

    require([
        'mainWidget',
        'widgetjs'
    ], function (mainWidget, widgetjs) {
        mainWidget.init(window.AccessiblySettings)
    });
</script>
